# Generated by Django 5.0.6 on 2024-07-05 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(09|\\+989)\\d{9}$", "Invalid Iranian phone number."
                    )
                ],
            ),
        ),
    ]
