# Generated by Django 4.1.6 on 2024-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_patient_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "permissions": [
                    ("is_patient", "User have access to patient dashboard"),
                    ("dashboard_access", "User has access to dashboard"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="patient",
            name="wallet",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
