# Generated by Django 4.1.6 on 2024-07-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_patient_options_alter_patient_wallet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["-created_at"]},
        ),
    ]
