# Generated by Django 5.0.7 on 2024-07-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otptoken"),
        ("accounts", "0004_alter_patient_options"),
    ]

    operations = []
