# Generated by Django 5.0.6 on 2024-07-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_merge_0003_otptoken_0004_alter_patient_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="951271", max_length=6),
        ),
    ]
