# Generated by Django 4.1.6 on 2024-07-11 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_alter_speciality_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"ordering": ("day_of_week",)},
        ),
        migrations.AlterField(
            model_name="speciality",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z]+$", "Specialty name must contain only letters."
                    )
                ],
            ),
        ),
    ]
