# Generated by Django 5.0.6 on 2024-07-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0003_alter_schedule_options_alter_speciality_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                unique=True,
            ),
        ),
    ]
